export const GET_ALL_ANIMALS = 'GET_ALL_ANIMALS'

export const SUCCESS_GET_ALL_ANIMALS = 'SUCCESS_GET_ALL_ANIMALS'

export const FAILED_GET_ALL_ANIMALS = 'FAILED_GET_ALL_ANIMALS'

export const GET_ANIMAL_DETAILS = 'GET_ANIMAL_DETAILS'

export const SUCCESS_GET_ANIMAL_DETAILS = 'SUCCESS_GET_ANIMAL_DETAILS'

export const FAILED_GET_ANIMAL_DETAILS = 'FAILED_GET_ANIMAL_DETAILS'
